<a href="https://colab.research.google.com/github/NatalyaKregel/11.08.22/blob/main/GoogleColabSeminar9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Задача 57 (семинар 9)
1. Прочесть с помощью файла pandas файл california_housing_test.csv, который находитяс в папке sample_data.
2. Помотреть сколько в нем строк и столбцов.
3. Определить, какой тип дннных имеют столбцы.

In [1]:
import pandas as pd

df = pd.read_csv('sample_data/california_housing_test.csv')
df.head() #первые 5 строчек

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0

In [2]:
df.isnull().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
dtype: int64

In [3]:
df.dtypes

longitude             float64
latitude              float64
housing_median_age    float64
total_rooms           float64
total_bedrooms        float64
population            float64
households            float64
median_income         float64
median_house_value    float64
dtype: object

##Задача 59 (семинар 9)
1. Проверить есть ли в файле пустые значения
2. Показать medium_house_value, где median_income>2
3. Показать данные в первых двух столбцах
4. Выбрать данные, где housing_median_age < 20 и housing_house_value > 70000

In [4]:
df.shape

(3000, 9)

In [3]:
import pandas as pd

df = pd.read_csv('sample_data/california_housing_test.csv')

In [6]:
#пункт 2
df[df['median_income']< 2]['median_income']

5       1.6635
6       1.6641
16      1.8750
28      1.5830
43      0.9838
         ...
2943    1.6563
2964    1.1434
2985    1.8633
2986    1.1346
2995    1.1790
Name: median_income, Length: 360, dtype: float64

In [7]:
#пункт 3
df[['longitude', 'latitude']]

      longitude  latitude
0       -122.05     37.37
1       -118.30     34.26
2       -117.81     33.78
3       -118.36     33.82
4       -119.67     36.33
...         ...       ...
2995    -119.86     34.42
2996    -118.14     34.06
2997    -119.70     36.30
2998    -117.12     34.10
2999    -119.63     34.42

[3000 rows x 2 columns]

In [8]:
df.iloc[0]

longitude               -122.0500
latitude                  37.3700
housing_median_age        27.0000
total_rooms             3885.0000
total_bedrooms           661.0000
population              1537.0000
households               606.0000
median_income              6.6085
median_house_value    344700.0000
Name: 0, dtype: float64

In [9]:
df.loc[(df['housing_median_age'] < 20) & (df['median_house_value'] > 70000)]

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0
7,-120.65,35.48,19.0,2310.0,471.0,1341.0,441.0,3.2250,166900.0
8,-122.84,38.40,15.0,3080.0,617.0,1446.0,599.0,3.6696,194400.0
13,-117.03,32.97,16.0,3936.0,694.0,1935.0,659.0,4.5625,231200.0
16,-120.81,37.53,15.0,570.0,123.0,189.0,107.0,1.8750,181300.0
...,...,...,...,...,...,...,...,...,...
2978,-121.34,38.64,17.0,2761.0,501.0,1128.0,482.0,3.7562,139700.0
2981,-120.66,35.49,17.0,4422.0,945.0,2307.0,885.0,2.8285,171300.0
2984,-117.59,33.88,13.0,3239.0,849.0,2751.0,813.0,2.6111,107000.0
2985,-120.47,34.94,17.0,1368.0,308.0,642.0,303.0,1.8633,109400.0
2991,-117.17,34.28,13.0,4867.0,718.0,780.0,250.0,7.1997,253800.0

## Задача 61 (семинар 9)
1. Определить какое максимальное и минимально значение median_house_value
2. Показать максимальное median_house_value, где median_income = 3.1250
3. Узнать какая максимальная population в зонеминимального значения median_house_value

In [10]:
df['median_house_value'].min(), df['median_house_value'].max()

(22500.0, 500001.0)

In [11]:
df['median_house_value'].describe()

count      3000.00000
mean     205846.27500
std      113119.68747
min       22500.00000
25%      121200.00000
50%      177650.00000
75%      263975.00000
max      500001.00000
Name: median_house_value, dtype: float64

In [16]:
df[df['median_income'] == 3.125]['median_house_value'].max()

233300.0

In [17]:
df[df['median_house_value'] == df['median_house_value'].max()]

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
42,-118.06,34.15,37.0,1980.0,226.0,697.0,226.0,15.0001,500001.0
117,-122.07,37.34,30.0,1851.0,238.0,631.0,236.0,10.1007,500001.0
118,-117.18,33.02,15.0,3540.0,453.0,1364.0,425.0,13.6623,500001.0
128,-122.47,37.79,52.0,2844.0,623.0,1380.0,596.0,4.7500,500001.0
135,-122.34,37.56,39.0,3562.0,391.0,1139.0,391.0,12.6417,500001.0
...,...,...,...,...,...,...,...,...,...
2960,-117.89,33.60,36.0,1496.0,247.0,441.0,203.0,7.8164,500001.0
2968,-119.23,34.17,18.0,6171.0,1490.0,2164.0,1210.0,3.6875,500001.0
2992,-122.33,37.39,52.0,573.0,102.0,232.0,92.0,6.2263,500001.0
2993,-117.91,33.60,37.0,2088.0,510.0,673.0,390.0,5.1048,500001.0
2999,-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0

In [18]:
df[df['median_house_value'] == df['median_house_value'].min()]['population'].max()

1230.0